/*
 * This source file was generated by the Gradle 'init' task
 */
package org.encli;

import picocli.CommandLine;

import org.encli.cli.*;

public class App {

    public static void main(String[] args) {
        try {
            int exitCode = new CommandLine(new CLI()).execute(args);
            System.exit(exitCode);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
}
