/*
 * This source file was generated by the Gradle 'init' task
 */
package org.encli;

import picocli.CommandLine;

import org.encli.cli.*;
import org.encli.exception.ExceptionHandler;

public class App {

    public static void main(String[] args) {
        ExceptionHandler handler = new ExceptionHandler();
        int exitCode = new CommandLine(new CLI()).setExecutionExceptionHandler(handler).execute(args);
        System.exit(exitCode);
    }
}
